"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// const user: (number | string)[] = [3, '3', 50, '33'];
var tUser;
tUser = ['shanu', 323, true];
var rgb = [23, 4, 6];
var newUser = [2, 'sh', true];
console.log(newUser);
newUser.unshift('shanu');
console.log(newUser);
